In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
x = np.array([10,20,30,40,50,60,70,80,90])
print(x)

[10 20 30 40 50 60 70 80 90]


In [ ]:
x = np.array([[10,20,30],[40,50,70]])
print(x)

[[10 20 30]
 [40 50 60]]


In [4]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
x = np.full((5,5,6),5)

print(x)

[[[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]

 [[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]

 [[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]

 [[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]

 [[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]]


In [7]:
x = np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [8]:
x=np.empty((5,8))
print(x)

[[6.95333550e-310 6.95333550e-310 6.95333550e-310 6.95333550e-310
  1.62053532e-319 4.43091394e-312 1.06086958e-311 1.06086958e-311]
 [6.95167695e-310 6.95167695e-310 0.00000000e+000 1.06088536e-311
  0.00000000e+000 6.91691904e-323 6.95328692e-310 2.02369289e-320]
 [6.91691904e-323 6.95328692e-310 3.95252517e-323 0.00000000e+000
  0.00000000e+000 1.00921564e-316 0.00000000e+000             nan]
 [0.00000000e+000 0.00000000e+000 1.69118923e-306 2.22522597e-306
  9.34607074e-307 7.56598449e-307 6.89790551e-307 9.34565652e-307]
 [1.16825035e-307 1.05695592e-307 7.56560423e-307 1.39075774e-307
  1.05695847e-307 1.33509185e-307 1.39071700e-307 1.24610927e-306]]


In [9]:
x=np.array([1,2,3])
y=np.array([1,2,3])

ans=x+y
print(ans)

[2 4 6]


In [10]:
x=np.array([[1,2,3],[8,9,10]])
y=np.array([[1,2,3],[8,9,10]])


ans=x+y
print(ans)

[[ 2  4  6]
 [16 18 20]]


In [11]:
x=np.array([[1,2,3],[8,9,10]])
y=np.array([[1,2,3],[8,9,10]])


ans=x-y
print(ans)

[[0 0 0]
 [0 0 0]]


In [12]:
x=np.array([[1,2,3],[8,9,10]])
y=np.array([[1,2,3],[8,9,10]])


ans=x*y
print(ans)

[[  1   4   9]
 [ 64  81 100]]


In [13]:
x=np.array([[1,2,3],[8,9,10]])
y=np.array([[1,2,3],[8,9,10]])


ans=x/y
print(ans)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# x=np.array([1,2,3])
y=np.array([1,2,3])

ans=np.sum(x)
print(ans)

33


In [15]:
x=np.array([1,2,3])
y=np.array([1,2,3])

ans=np.add(x,y)
print(ans)

[2 4 6]


In [16]:
x= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
ans1=np.sum(x)
print(ans1)
ans2=np.sum(x,axis=0)
print(ans2)
ans3=np.sum(x,axis=1)
print(ans3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [17]:
x=np.array([10,20,45,60,78,45,30])
ans=np.mean(x)
print(ans)

41.142857142857146


In [18]:
x=np.array([10,20,45,60,78,45,30])
ans=np.median(x)
print(ans)

45.0


In [19]:
x=np.array([10,20,45,90,78,65,20,20])

ans=np.std(x)
print(ans)
ans2=np.max(x)
print(ans2)
ans3=np.min(x)
print(ans3)

28.71410803072246
90
10


In [20]:
x= np.array([[1,2,3],[4,5,6],[7,8,9]])
ans=np.max(x)


#slicing

In [21]:
arr = np.array([1,2,3,4,5])
print(arr[1])
print(arr[1:])
print(arr[:3])
print(arr[1:])
print(arr[1::2])
print(arr[::])

2
[2 3 4 5]
[1 2 3]
[2 3 4 5]
[2 4]
[1 2 3 4 5]


reshape data

In [22]:
a = np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
a1 = a.reshape(2,3)
print(a1)
a2 = a.reshape(3,2)
print(a2)

print(a2.shape)
# for reshape array 
x = np.arange(12)
print(x)

ans = x.reshape(3,2,2)
print(ans)

x1 = x.reshape(3,-1)
print(x1)


# np.reshape(array,new_arary)


[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


flatten

In [23]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)
a1= a.flatten()
print(a1)
print(a1.shape)

x3 = np.arange(12).reshape(3,4)
print(x3)

x11 = x3.flatten(order="A")
print(x11)
 
x12 = x3.flatten(order="C")
print(x12)

x13 = x3.flatten(order="F")
print(x13)

x14 = x3.flatten(order="k")
print(x14)




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  8  1  5  9  2  6 10  3  7 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


random

In [24]:
a = np.random.rand(3,4)
print(a)

[[0.43082471 0.05530858 0.42597222 0.38283078]
 [0.15800169 0.40958029 0.80980272 0.37997578]
 [0.42556956 0.8503488  0.0497355  0.38581132]]


# 🔢 NumPy Practice Questions (Medium Level)

In [25]:
# 1. Array Creation
# Create a NumPy array of numbers from 1 to 20. Then print its size.

a = np.arange(1,21)
print(a)
print(a.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
20


In [26]:
# 2. Zeros & Ones
# Create:

# a 3×4 array filled with zeros

zeros_arr = np.zeros((3, 4))
print(zeros_arr)

# a 2×5 array filled with ones

ones_arr = np.ones((2, 5))
print(ones_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
# 3. Full Function
# Create a 4×4 array where every value is 7 using NumPy.

full_arr = np.full((4, 4), 7)
print(full_arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [28]:
# 4. Reshape
# Create an array from 1 to 12 and reshape it into:


# 3×4

# 2×6

arr = np.arange(1, 13)

arr_3x4 = arr.reshape(3, 4)
arr_2x6 = arr.reshape(2, 6)

print(arr_3x4)
print(arr_2x6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [29]:
# 5. Flatten
# Take a 3×3 matrix and convert it into a 1D array using flatten.

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
flat_arr = matrix.flatten()
print(flat_arr)

[1 2 3 4 5 6 7 8 9]


In [30]:

# 6. Arrange (arange)
# Create an array starting from 10 to 50 with a step of 5.

arr = np.arange(10, 51, 5)
print(arr)


[10 15 20 25 30 35 40 45 50]


In [31]:

# 7. Sum of Elements
# Given array:
# [10, 20, 30, 40, 50]
# Find:
# total sum


# sum of first 3 elements only
arr = np.array([10, 20, 30, 40, 50])

print("Total sum:", np.sum(arr))
print("First 3 sum:", np.sum(arr[:3]))



Total sum: 150
First 3 sum: 60


In [32]:

# 8. Matrix Addition
# Add the following two arrays:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[6,5,4],[3,2,1]])

add = A + B
print(add)

[[7 7 7]
 [7 7 7]]


In [33]:
# 9. Matrix Subtraction
# Subtract array B from array A (from Q8).

sub = A - B
print(sub)

[[-5 -3 -1]
 [ 1  3  5]]


In [34]:
# 10. Element-wise Multiplication
# Multiply arrays A and B element by element.
mul = A * B
print(mul)


[[ 6 10 12]
 [12 10  6]]


In [35]:
# 11. Mean
# Find the mean of:
# [12, 15, 20, 25, 30]
arr = np.array([12, 15, 20, 25, 30])
print("Mean:", np.mean(arr))


Mean: 20.4


In [36]:

# 12. Median
# Find the median of:
# [5, 2, 9, 1, 7, 6]
arr = np.array([5, 2, 9, 1, 7, 6])
print("Median:", np.median(arr))

Median: 5.5


In [37]:

# 13. Standard Deviation
# Find the standard deviation of:
# [4, 8, 6, 5, 3, 7]
arr = np.array([4, 8, 6, 5, 3, 7])
print("Std Dev:", np.std(arr))

Std Dev: 1.707825127659933


In [38]:
# 14. Row-wise Sum
# Given matrix:

# [[1,2,3],
#  [4,5,6],
#  [7,8,9]]

# Find sum of each row separately.
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
row_sum = np.sum(matrix, axis=1)
print(row_sum)

[ 6 15 24]


In [39]:

# 15. Column-wise Sum
# Using the same matrix from Q14, find sum of each column.
col_sum = np.sum(matrix, axis=0)
print(col_sum)


[12 15 18]


In [40]:

# 16. Reshape + Mean
# Create numbers from 1 to 16, reshape into 4×4, then find the mean of each row.

arr = np.arange(1, 17).reshape(4, 4)
row_mean = np.mean(arr, axis=1)
print(row_mean)

[ 2.5  6.5 10.5 14.5]


In [41]:
# 17. Flatten + Size
# Create a 5×5 ones matrix. Flatten it and find its size.
arr = np.ones((5, 5))
flat = arr.flatten()

print(flat)
print("Size:", flat.size)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]
Size: 25


In [42]:

# 18. Arithmetic Combination
# Given:
# A = [1,2,3,4]
# B = [5,6,7,8]

# Compute:
# (A + B) * 2
A = np.array([1,2,3,4])
B = np.array([5,6,7,8])

result = (A + B) * 2
print(result)


[12 16 20 24]


In [43]:

# 19. Mixed Operations
# Create array from 1–9, reshape to 3×3. Multiply entire matrix by 5 and then find total sum.

arr = np.arange(1, 10).reshape(3, 3)
result = arr * 5

print(result)
print("Total sum:", np.sum(result))

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Total sum: 225


In [44]:

# 20. Statistics Combo
# Given:
# [15, 18, 21, 24, 27, 30]

# Find:

# mean

# median

# standard deviation

arr = np.array([15, 18, 21, 24, 27, 30])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std Dev:", np.std(arr))


Mean: 22.5
Median: 22.5
Std Dev: 5.123475382979799


# hard

In [45]:
# 1. Advanced Reshape + Sum

# Create an array from 1 to 48.

ary = np.arange(1,49)
print(ary)

# Reshape it into 4 × 4 × 3.

x = ary.reshape(4,4,3)
print(x)


# Find:

# sum along axis 0
print("answer 1")
ans1= x.sum(axis=0)
print(ans1)
# sum along axis 1
print("answer 2")
ans2= x.sum(axis=1)
print(ans2)
# sum along axis 2
print("answer 3")
ans3= x.sum(axis=2)
print(ans3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]
answer 1
[[ 76  80  84]
 [ 88  92  96]
 [100 104 108]
 [112 116 120]]
answer 2
[[ 22  26  30]
 [ 70  74  78]
 [118 122 126]
 [166 170 174]]
answer 3
[[  6  15  24  33]
 [ 42  51  60  69]
 [ 78  87  96 105]
 [114 123 132 141]]


In [46]:
# 2. Conditional Replacement

# Create array from 1 to 20.

arr = np.arange(1,21)
print(arr)
# Replace all numbers:



# divisible by 3 → -1
arr[arr % 3 == 0] = -1

# divisible by 5 → 100
arr[arr % 5 == 0] = 100

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   2  -1   4 100  -1   7   8  -1 100  11  -1  13  14  -1  16  17  -1
  19 100]


In [47]:
# 3. Broadcasting Math

# Given:

# A = np.array([[1,2,3],
#               [4,5,6],
#               [7,8,9]])


# B = np.array([10,20,30])

# Add B to every row of A using broadcasting.

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([10,20,30])

result = A + B
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [48]:
# 5. Indexing Challenge

# Create array 1–25 and reshape to 5×5.
# Extract:
ary=np.arange(1,26).reshape(5,5)
print(ary)

# middle row
print(ary[2:3:3])
# last column
print(ary[::,4::4])
# corner elements only
print(ary[::4,::4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[11 12 13 14 15]]
[[ 5]
 [10]
 [15]
 [20]
 [25]]
[[ 1  5]
 [21 25]]


In [49]:
# 8. Pattern Matrix

# Create this matrix using NumPy only:

# [[1,0,1,0],
#  [0,1,0,1],
#  [1,0,1,0],
#  [0,1,0,1]]

# (No manual typing.)

ary = np.arange(0,25).reshape(5,5)
print(ary)

ary[ary % 2 == 0] = 0
ary[ary % 2 != 0] = 1
print(ary)

print(ary[:4,:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [50]:










# 4. Flatten vs Ravel Logic

# Create a 3×3 matrix.
# Use ravel() to flatten and modify the first element.
# Then check whether original array changes.
# Explain why.



# 6. Statistical Axis Problem

# Given:

# arr = np.array([[10,20,30],
#                 [40,50,60],
#                 [70,80,90]])

# Find:

# mean of each column

# standard deviation of each row

# 7. Matrix Arithmetic Combo

# Create two random 3×3 arrays.
# Compute:

# (A + B) * 2 - A



# 9. 3D Array Stats

# Create array from 1–27 and reshape to 3×3×3.
# Find:

# overall mean

# mean along axis 0

# median of entire array

# 10. Multi-step Transformation

# Create array from 1–16.
# Steps:

# Reshape to 4×4

# Multiply each column by [1,2,3,4]

# Flatten result

# Find standard deviation

In [51]:
x = np.arange(1,49).reshape(4,4,3)
print(x)
print("1")
ans=np.sum(x,axis=0)
print(ans)
print("1")

ans1=np.sum(x,axis=1)
print(ans1)
print("1")

ans2=np.sum(x,axis=2)
print(ans2)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]
1
[[ 76  80  84]
 [ 88  92  96]
 [100 104 108]
 [112 116 120]]
1
[[ 22  26  30]
 [ 70  74  78]
 [118 122 126]
 [166 170 174]]
1
[[  6  15  24  33]
 [ 42  51  60  69]
 [ 78  87  96 105]
 [114 123 132 141]]


In [52]:
a = np.arange(1,26).reshape(5,5)
print(a)
print(a[4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[21 22 23 24 25]


In [53]:
# Create array 1–25 and reshape to 5×5.
# Extract:
ary=np.arange(1,26).reshape(5,5)
print(ary)

# middle row
print(ary[3:4])

# last column
print(ary[:,4:])
# corner elements only

print(ary[0::4,0::4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[16 17 18 19 20]]
[[ 5]
 [10]
 [15]
 [20]
 [25]]
[[ 1  5]
 [21 25]]
